name: Merge main into release branch
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseBranchName:
        description: "Branch to follow releases"
        required: true
        default: "release"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref}}
      - name: Merge release into release branch
        run: |
          git fetch
          git switch "${{inputs.releaseBranchName}}"
          git merge --ff-only "${{ github.ref_name}}"
          git push -f
