name: Merge current release into release branch
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      releaseBranchName:
        description: "Branch to follow releases"
        type: string

permissions:
  contents: write

jobs:
  merge:
    name: Merge "${{ github.ref_name}}" into "${{ inputs.releaseBranchName || vars.RELEASE_BRANCH_NAME || 'release' }}"
    runs-on: ubuntu-latest
    env:
      RELEASE_BRANCH_NAME: ${{ inputs.releaseBranchName || vars.RELEASE_BRANCH_NAME || 'release' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge release into release branch
        run: |
          git fetch
          git checkout "${{env.RELEASE_BRANCH_NAME}}"
          git status
          git merge --ff-only "${{ github.ref_name}}"
          git push -f
